### PR TITLE
Textures: Chests, Droppers, Doors, Cactus, Biome-specific colors.

### PR DESCRIPTION
**Pull request by MC42**
Added or FIxed:
* Redstone Torches
* Redstone Repeaters
* Mossy Cobblestone.
* Single Chests
* Double Chests
* Birch Logs
* Sponges
* Dropper
* Piston (Back)
* Piston (Top)
* Sticky Piston (Top)
* Obsidian
* Tilled Soil (added till lines)
* Roses
* 

Finished Rails

### CODE REVIEW

**Comment by MC42** [comment]
I have no idea how the build failed when all I did was change an image...

**Comment by SirCmpwn** [comment]
The build failed because travis was being stupid.

Don't make the leaves greyscale - TrueCraft doesn't do biome tinting yet.

**Comment by SirCmpwn** [comment]
It all looks good, but the chests could be a bit darker and have stronger edges (to look closer to vanilla) in my opinion.

**Comment by RockyTV** [comment]
@SirCmpwn I have a suggestion. There's 3 types of wood planks, right? If you craft a chest with oak wood, the chest color should be normal. With birch, it should be lighter, and with pine, it should be darker.

**Comment by MC42** [comment]
I'll fix the textures back from the previous version for biome-specific colors.

**Comment by SirCmpwn** [comment]
@RockyTV in beta 1.7.3 there's only one kind of wooden planks.

**Comment by MC42** [comment]
I fixed the biome colors in this one now.  They're back to what they were before, but everything else I changed is there.

**Comment by SirCmpwn** [comment]
Cool. Thanks!

**Comment by SirCmpwn** [comment]
@MC42 make sure you pull before you make more changes or you'll have merge conflicts.

**Pull request merged**
