### PR TITLE
Add Mac OSX Support

### PR DESCRIPTION
**Pull request by Gbear605**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Have you ever read the decompiled Minecraft source code?

This doesn't seem to include the post build step that copies the OSX DLL into the bin directory, and seems to be missing launcher support.

**Comment by Gbear605** [comment]
I have never read the decompiled Minecraft source code. Launcher support is indeed currently missing, but this is a first step that gets the client to work on Mac. I did not need any post build step to copy the OSX DLL into the bin directory.

**Comment by SirCmpwn** [comment]
The post build step is necessary for when a different target builds your binaries (for example, the build server). You'll have to add it not for your own sake but for the sake of portable builds.

**Comment by Gbear605** [comment]
I've added the post build step now.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
