### PR TITLE
Added support for changing preferred resolution in options

### PR DESCRIPTION
**Pull request by mrpimpunicorn**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
I'd rather not make users type in their preference. Can we populate a dropdown with common resolutions instead?

**Comment by mrpimpunicorn** [comment]
Sure, sounds good. More advanced users could just edit settings.json manually if needed.

**Comment by SirCmpwn** [comment]
Can we go up higher? Notably missing:

* 1920x1080
* 1920x1200
* 4K

**Comment by SirCmpwn** [comment]
How about a windowed option while we're at it, too?

**Comment by mrpimpunicorn** [comment]
Sure.

**Comment by mrpimpunicorn** [comment]
I've added the missing resolutions and a fullscreen option, but MonoGame seems to ignore Graphics.IsFullScreen and stays windowed.

**Comment by SirCmpwn** [comment]
`Graphics.IsFullScreen` seems to work for me.

**Comment by SirCmpwn** [comment]
Yeah, just tried your changes out and it worked fine for me. :smile:

**Comment by mrpimpunicorn** [comment]
Weird. We should open an issue to address it later, if someone else can confirm it's a Windows thing.

**Comment by SirCmpwn** [comment]
Sounds good, feel free to open one describing your symptoms.

**Pull request merged**
