### PR TITLE
Update NuGet packages

### PR DESCRIPTION
**Pull request by cra0zy**
Does ~~3~~ 1 thing:
 - Updates NuGet packages
 - ~~Updates Xwt dlls, also moves them all to lib folder, they were all over the place...~~
 - ~~Adds Xwt Gtk3 lib for Linux~~

PS. I couldn't get it to compile without updating the nuget packages, duno why
PPS. Before you ask, I did manually call "Restore NuGet packages" just in case

### CODE REVIEW

**Comment by SirCmpwn** [comment]
I can't merge your DLLs (can't be sure there aren't nasty things in them), but I'd merge your NuGet changes and update the DLLs myself.

**Comment by cra0zy** [comment]
> I can't merge your DLLs (can't be sure there aren't nasty things in them), but I'd merge your NuGet changes and update the DLLs myself.

Ok, will modify the PR in a moment.

Can you add Xwt.Gtk3 binary for Linux?

**Comment by SirCmpwn** [comment]
Assuming I can get it to build, yes. Last time I tried the build didn't work and I didn't research it any further.

**Comment by cra0zy** [comment]
> Assuming I can get it to build, yes. Last time I tried the build didn't work and I didn't research it any further.

I fixed it an hour ago :P
https://github.com/mono/xwt/pull/588

**Comment by SirCmpwn** [comment]
Haha, nice.

**Comment by cra0zy** [comment]
@SirCmpwn done

**Comment by SirCmpwn** [comment]
Looks good. I will build+update Xwt later tonight.

**Pull request merged**
