### PR TITLE
Removed non-beta textures, fixed cacti, flowers, rails, bed, nether stuff, redstone.

### PR DESCRIPTION
**Pull request by MC42**
Glowstone 
Beds     
Pumpkins 
Redstone  
Csctus   
Netherrack
Soulsand

Extra: Removed items not in version.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
There are merge conflicts that need to be resolved before I can accept this pull request.

**Comment by MC42** [comment]
I'm not quite sure I understand... Do I need to recopy the folder from your repo, and apply the new image over it?

**Comment by SirCmpwn** [comment]
[Link](https://encrypted.google.com/search?hl=en&q=how%20to%20resolve%20git%20merge%20conflicts)

**Comment by MC42** [comment]
That doesn't really help... I just cloned my branch of the repo locally, pushed it there via git, and then submitted a pull request via the web portal.  Any ideas?

**Comment by SirCmpwn** [comment]
I guess the easiest way would be to make a fresh fork and just toss your current texture into it.

**Pull request closed without merging**
