### PR TITLE
Do lighting updates on client as blocks change

### PR DESCRIPTION
**Pull request by TopHatProductions115**
I have a Macbook 4,1 - OS X 10.10.5
http://osxhackers.net/macpostfactor.html

Could I be of assistance?

### CODE REVIEW

**Comment by SirCmpwn** [comment]
What are you trying to do here?

**Comment by TopHatProductions115** [comment]
I found an article stating that you were looking for someone to compile an
OS X version of TrueCraft. Is this the case?

**Comment by SirCmpwn** [comment]
Yes. What does this PR have to do with that?

**Comment by TopHatProductions115** [comment]
If this is the incorrect address for me to use, I apologize. Please help.

**Pull request closed without merging**
