### PR TITLE
Case sensitivity fix + camera logic encapsulation

### PR DESCRIPTION
**Pull request by mrpimpunicorn**
Accidentally disabled VS' hosting process, so the third commit fixes that.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
I love the camera change, but you're right that it should be on its own. Try this:

    # This checks out a branch named "fix-case-sensitivity"
    git checkout -b fix-case-sensitivity
    # This removes the past three commits so you can do it cleanly
    git reset --hard HEAD~3
    # This grabs the only commits you want
    git cherry-pick 2b1bf08
    git cherry-pick 2075244
    # This will merge the two commits together, as if you hadn't made the VS hosting process mistake
    git rebase -i HEAD~2
    # This pushes your branch. Make a pull request after you push this.
    git push -u origin fix-case-sensitivity
    # New branch for camera work, based on master
    git checkout -b isolate-camera master
    git reset --hard HEAD~3
    # Pick just that commit
    git cherry-pick de1ffa2
    # Push and open second pull request
    git push -u origin isolate-camera
    # Finally, we can remove the commits from master so that your master branch doesn't get fucked up when we merge
    git checkout master
    git reset --hard HEAD~3

**Comment by mrpimpunicorn** [comment]
Okay, I've run the commands, so I'll just add pull requests for both branches then?

**Comment by SirCmpwn** [comment]
In theory, yes, but looking at your fork it appears that you've done it wrong. On second thought, I'm going to merge both anyway, so who cares.

**Comment by mrpimpunicorn** [comment]
Sorry, command-line GIT is not my forte.

**Comment by SirCmpwn** [comment]
No worries.

**Pull request merged**
