### PR TITLE
Add list command

### PR DESCRIPTION
**Pull request by Peroalane**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Does this match the output of the vanilla server's implementation of the same command?

**Comment by Peroalane** [comment]
Yes, according to the wiki.

http://minecraft.gamepedia.com/Commands#list

**Comment by Peroalane** [comment]
With the exception of the UUID stuff.

**Comment by SirCmpwn** [comment]
I mean that I'm not sure that "Current online players: " is present on the official server, nor do I really like it. Another concern is: what if the list of players is longer than the maximum length of a chat message? You'll need to split it up.

**Comment by Peroalane** [comment]
I'll change it a bit then.

**Comment by Peroalane** [comment]
What is the maximum length?

**Comment by SirCmpwn** [comment]
I don't recall, google it.

**Comment by Peroalane** [comment]
Okay to merge now?

**Comment by SirCmpwn** [comment]
I would prefer that you sent multiple chat messages that were, individually, no longer than the maximum length, rather than just not sending the list if there are too many players.

**Comment by Peroalane** [comment]
Me too, but at least the command works :) There's no harm in merging it.

**Comment by SirCmpwn** [comment]
That's not how it works.

**Pull request closed without merging**
