### PR TITLE
Added support for chat colors in FontRenderer

### PR DESCRIPTION
**Pull request by mrpimpunicorn**
screenshot client 0

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Nice! I'll merge this once the build passes.

**Comment by SirCmpwn** [comment]
If you have interest in working more on FontRenderer, it needs to be made much more versatile. We should be able to control the font size, too, and the font needs to be replaced with a more Minecrafty font (see #82).

**Comment by UnknownShadow200** [comment]
Uppercase a-f colour codes aren't recognised.

**Comment by mrpimpunicorn** [comment]
I've got a fix for it in a commit now, and I'll work some more on the FontRenderer as well. The commit is on top another unrelated one however, can I split them up?

**Comment by SirCmpwn** [comment]
It's hard to answer that question without seeing the commits, so send the pull request along and we'll address it then if it's a problem.

**Pull request merged**
