### PR TITLE
Made client work on Windows

### PR DESCRIPTION
**Pull request by robinkanters**
Please verify that the client still runs on linux

### CODE REVIEW

**Comment by SirCmpwn** [comment]
LGTM. Thanks!

**Comment by SirCmpwn** [comment]
At some point we'll want to change the name of the project to `TrueCraft.Client`.

**Comment by robinkanters** [comment]
Yeah, but I felt like making it work was more important than renaming (and restructuring) the solution. I wanted to discuss naming first anyway

**Comment by SirCmpwn** [comment]
Yep, agreed.

**Pull request merged**
