### PR TITLE
Shaders

### PR DESCRIPTION
**Pull request by mrpimpunicorn**
While it really doesn't do anything more than ```BasicEffect``` did, it still opens the rendering pipeline up to more optimizations/features/etc.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
The `mgfx` file needs to be generated at build time, not checked into source control.

**Comment by mrpimpunicorn** [comment]
Probably, I don't know how to do that in a cross-platform way though. I think MonoGame would also have to then be installed on any system that wants to build TrueCraft, as well.

**Comment by SirCmpwn** [comment]
We can probably just copy the `mcgb` binary into the repo, that's fine with me.

**Comment by mrpimpunicorn** [comment]
That works, do you want me to put the binaries in a ```/tools``` directory?

**Comment by SirCmpwn** [comment]
Sure, good plan.

**Comment by mrpimpunicorn** [comment]
Feel free to add the appropriate linux binaries as well, the last step is the one I don't understand. How do we process all ```.fx``` files as a post-build step?

**Comment by SirCmpwn** [comment]
We can do it in a pre-build step, but hold on. 2MGFX will indeed *not* work on Linux.

Let's look into how FNA does it. Wiki link: https://github.com/flibitijibibo/FNA/wiki/2:-Building-with-FNA

**Comment by SirCmpwn** [comment]
Paging @flibitijibibo for comment.

**Comment by flibitijibibo** [comment]
I usually build effects on Linux with fxc.exe, found within the DirectX SDK - it actually works with the current Wine version! On Windows you can of course run it directly, but on Linux (and this _should_ run on OSX) I build with these scripts:

https://github.com/flibitijibibo/EffectRE/blob/master/buildEffect.sh
https://github.com/flibitijibibo/EffectRE/blob/master/buildEffects.sh

It's not native, but it's heaps nicer than having to reboot to Win32!

I think the MonoGame team is planning on redoing the MGFX subsystem entirely to support any shading language and not require the Win32-specific parts, but given the difficulty of the task and the fact that it Just Works for developers at the moment, I dunno when that'll happen.

**Comment by SirCmpwn** [comment]
Is it possible to just use OpenGL on Windows and use GLSL instead of HLSL?

**Comment by mrpimpunicorn** [comment]
You can choose what graphics API you use when you create a MonoGame template, but I don't think that changes how the .fx files are interpreted.

**Comment by SirCmpwn** [comment]
Possibly useful resource:

http://aras-p.info/blog/2014/03/28/cross-platform-shaders-in-2014/

**Comment by flibitijibibo** [comment]
I think that's their plan with MGFX2, but at the moment you can't. FNA doesn't support it either since MojoShader's pretty deeply integrated into the Effect implementation and the OpenGLDevice. But, on the bright side, once I have access to a Vulkan driver I'll be writing a SPIR-V emitter for MojoShader and a VulkanDevice, so both Vulkan and OpenGL can be supported with a single binary. That's a ways off, but it'll at least sweeten the deal in exchange for getting hitched to HLSL.

**Comment by SirCmpwn** [comment]
God dammit! This whole mess is gross. I don't think there is any solution here. We can't distribute fxc.exe.

**Comment by flibitijibibo** [comment]
Yeah, it's a real mess. MICROSOFT TECHNOLOGIES~<3

**Comment by SirCmpwn** [comment]
I'm not going to merge this if folks on all platforms can't compile it and hack on it. We'll stick to BasicEffect until MonoGame gets their shit together.

**Comment by mrpimpunicorn** [comment]
Probably the best option for now. There is also always the refactoring-exhaustive option of moving down an abstraction level to OpenTK. No future issues with platform-compatibility.

**Comment by SirCmpwn** [comment]
If you'd like to put together a migration plan for OpenTK, I'd definitely consider it.

**Comment by mrpimpunicorn** [comment]
Will do.

**Comment by SirCmpwn** [comment]
@mrpimpunicorn I'm interested in pursuing this again. I would like to make a windows server that you can send a shader to and have the result sent back to you. Is this feasible? What's the procedure for compiling a shader on Windows?

**Comment by mrpimpunicorn** [comment]
It's feasible, when I went to compile the shader I needed a development build of MonoGame to do so. You basically pass input and output paths to a cmd-line tool. I'll check out my setup when I get to my computer.

**Pull request closed without merging**
