### PR TITLE
New Textures : Wool done, trapdoor, iron door, spawner, wheat, other misc. tweaks to existing textures.

### PR DESCRIPTION
**Pull request by MC42**
Added:
* Wools are textures
* New wheat textures.
* Iron doors textures.
* Trapdoor texture.
* Cobweb texture.
Currently Working On:
*Rail Line set.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Shall I leave this pull request open until you're done or merge now?

**Comment by SirCmpwn** [comment]
Also, I'd appreciate it if you used more descriptive commit messages.

**Comment by MC42** [comment]
I'm using comments currently, but I'll put the items changed in the topic now.

**Comment by MC42** [comment]
I'm done for today.
No more for ~12-24 hours.

**Comment by MC42** [comment]
If you want to pull it, go ahead.

**Comment by SirCmpwn** [comment]
Cool, thanks.

**Pull request merged**
