### PR TITLE
Cleanup QueryProtocol

### PR DESCRIPTION
**Pull request by Mitch528**
- Dispose of streams
- Use ConcurrentDictionary

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Thanks. Will do a quick test to make sure everything's great and then will merge.

**Comment by SirCmpwn** [comment]
Good thing I tested - something you've done in this pull request has broken the functionality of this feature.

**Comment by Mitch528** [comment]
What did you use to test it?

**Comment by SirCmpwn** [comment]
https://github.com/Dinnerbone/mcstatus

**Comment by Mitch528** [comment]
Should be fixed now.

**Comment by SirCmpwn** [comment]
:tada:

**Pull request merged**
