### PR TITLE
Add: Helper methods for obtaining block's X and Z chunk coordinates give...

### PR DESCRIPTION
**Pull request by sgtbigman**
...n block's world coordinates.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Thanks!

**Comment by SirCmpwn** [comment]
I should have tested these two pull requests more carefully. They break things. Reverted.

**Comment by sgtbigman** [comment]
Odd, really unsure of how the PRs would break anything. Anything you were running into in particular?

**Comment by SirCmpwn** [comment]
Yep - remember when I warned you that "it's not that simple" and talked about negative numbers and such? Well, it really isn't that simple, and this breaks when you try to fetch a block at `<-5, 0, -5>`.

**Comment by sgtbigman** [comment]
Yep, I remember, and now I see how that case would break this PR. I do believe #53 should have been fine, though; nevertheless, I understand reverting both for now. Thanks for catching the breakage; I'll look into more thorough testing on my end.

**Pull request merged**
