### PR TITLE
Added support for texture packs

### PR DESCRIPTION
**Pull request by mrpimpunicorn**
A bit of a rough piece of code; I've never used Xwt before.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Awesome! This will require a manual review, so it'll take a minute to process.

My first bit of feedback is this - I'd strongly prefer for the client to pull resources out of the archive rather than having the launcher extract the archive to `Content`. What if the launcher doesn't have permission to write to Content (for example, if it was installed in Program Files or whatever the case my be)?

**Comment by mrpimpunicorn** [comment]
Good point, I was originally going to do it like that but thought that since you had put the singleplayer and multiplayer menus in the launcher that all that kind of functionality would be there too. Another issue I was concerned about was accidentally extracting malicious files that aren't part of the texture pack spec (like mypack/autoextractrar.jpg)

**Comment by mrpimpunicorn** [comment]
If I move the texture loading to the client, should I just pass the texture pack path as a command-line argument?

**Comment by SirCmpwn** [comment]
At this point we're pushing it with how much we pass on the command line. How about we put it in `settings.json` and move `UserSettings` to `TrueCraft.Core`?

**Comment by SirCmpwn** [comment]
Oh, and let's install texture packs to `~/.truecraft/texturepacks/` for stronger Minecraft compatability. We can have the launcher receive drag-and-drop texture packs and copy them there for better usability if need be.

**Comment by mrpimpunicorn** [comment]
Sounds good, I'll start rewriting the necessary portions of the code, tell me if you come up with anything else.

**Comment by mrpimpunicorn** [comment]
Moving UserSettings means TrueCraft.Core needs Newtonsoft.Json, can I import it through NuGet?

**Comment by SirCmpwn** [comment]
Sure.

**Comment by mrpimpunicorn** [comment]
Okay, now the launcher searches through ./truecraft/texturepacks/ for zip files and the client loads them, but I've also kept the default texture pack in the content directory so that it will always be an option even if the user clears/deletes the texture pack directory.

**Comment by SirCmpwn** [comment]
Beautiful. I'll have to test this manually, and now is not a good time, but I will merge this once it is good to go.

As an aside, updating the zip file whenever we update the default textures is going to be a pain. If you have time before I test and merge this, can you look into ways to avoid doing that? Perhaps the default pack can be a special case that does not use a zip file.

**Comment by mrpimpunicorn** [comment]
Yeah, we can have a sort of TexturePackMapper class, which provides 'default' texture values when created without a texture pack, but when provided with a custom one, routes texture loading through the pack's zip file.

**Comment by SirCmpwn** [comment]
The reason I ask is because you did create a zip file and added it to `Content`. What's it there for if the `TexturePackMapper` works without it?

**Comment by mrpimpunicorn** [comment]
I haven't wrote the class yet, so the zip is just there to keep things working.

**Comment by SirCmpwn** [comment]
Ah, alright. I'll get this merged up then ASAP.

**Comment by SirCmpwn** [comment]
Launcher only works if Content is available in the working directory (not always the case). Even if it is, though:

    sircmpwn@kyouko ~/s/T/T/b/Debug (HEAD detached at mrpimpunicorn/master)> mono --debug TrueCraft.Launcher.exe
    Unhandled Exception:
    GLib.GException: Unrecognized image file format
      at Gdk.PixbufLoader.Close () [0x00035] in /build/gtk-sharp-2/src/gtk-sharp-2.12.22/gdk/generated/PixbufLoader.cs:294 
      at Gdk.PixbufLoader.InitFromStream (System.IO.Stream stream) [0x00022] in /build/gtk-sharp-2/src/gtk-sharp-2.12.22/gdk/generated/PixbufLoader.custom:82 
      at Gdk.PixbufLoader..ctor (System.IO.Stream stream) [0x00009] in /build/gtk-sharp-2/src/gtk-sharp-2.12.22/gdk/generated/PixbufLoader.custom:71 
      at Xwt.GtkBackend.ImageHandler.LoadFromStream (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
      at Xwt.Drawing.Image.FromStream (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
      at TrueCraft.Launcher.Views.OptionView.AddTexturePackRow (TrueCraft.Core.TexturePack pack) [0x00020] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Views/OptionView.cs:116 
      at TrueCraft.Launcher.Views.OptionView.LoadTexturePacks () [0x0001a] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Views/OptionView.cs:95 
      at TrueCraft.Launcher.Views.OptionView..ctor (TrueCraft.Launcher.LauncherWindow window) [0x001bf] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Views/OptionView.cs:81 
      at (wrapper remoting-invoke-with-check) TrueCraft.Launcher.Views.OptionView:.ctor (TrueCraft.Launcher.LauncherWindow)
      at TrueCraft.Launcher.LauncherWindow..ctor () [0x0006f] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/LauncherWindow.cs:35 
      at (wrapper remoting-invoke-with-check) TrueCraft.Launcher.LauncherWindow:.ctor ()
      at TrueCraft.Launcher.Program.Main (System.String[] args) [0x00080] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Program.cs:27 
    [ERROR] FATAL UNHANDLED EXCEPTION: GLib.GException: Unrecognized image file format
      at Gdk.PixbufLoader.Close () [0x00035] in /build/gtk-sharp-2/src/gtk-sharp-2.12.22/gdk/generated/PixbufLoader.cs:294 
      at Gdk.PixbufLoader.InitFromStream (System.IO.Stream stream) [0x00022] in /build/gtk-sharp-2/src/gtk-sharp-2.12.22/gdk/generated/PixbufLoader.custom:82 
      at Gdk.PixbufLoader..ctor (System.IO.Stream stream) [0x00009] in /build/gtk-sharp-2/src/gtk-sharp-2.12.22/gdk/generated/PixbufLoader.custom:71 
      at Xwt.GtkBackend.ImageHandler.LoadFromStream (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
      at Xwt.Drawing.Image.FromStream (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
      at TrueCraft.Launcher.Views.OptionView.AddTexturePackRow (TrueCraft.Core.TexturePack pack) [0x00020] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Views/OptionView.cs:116 
      at TrueCraft.Launcher.Views.OptionView.LoadTexturePacks () [0x0001a] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Views/OptionView.cs:95 
      at TrueCraft.Launcher.Views.OptionView..ctor (TrueCraft.Launcher.LauncherWindow window) [0x001bf] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Views/OptionView.cs:81 
      at (wrapper remoting-invoke-with-check) TrueCraft.Launcher.Views.OptionView:.ctor (TrueCraft.Launcher.LauncherWindow)
      at TrueCraft.Launcher.LauncherWindow..ctor () [0x0006f] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/LauncherWindow.cs:35 
      at (wrapper remoting-invoke-with-check) TrueCraft.Launcher.LauncherWindow:.ctor ()
      at TrueCraft.Launcher.Program.Main (System.String[] args) [0x00080] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Program.cs:27

**Comment by mrpimpunicorn** [comment]
Huh, looks like it can't read the texture pack image; but it's just a regular PNG loaded into a MemoryStream. I'll check it out.

**Comment by SirCmpwn** [comment]
Tested it on Linux, for what it's worth. Might behave differently from Windows.

**Comment by SirCmpwn** [comment]
Ah, I found the problem. You need to seek the memory stream back to the start.

**Comment by mrpimpunicorn** [comment]
Thanks, that makes perfect sense now. Weird that my runtime didn't throw an exception; stream position being in the wrong place usually ruins everybody's day.

**Comment by SirCmpwn** [comment]
Another problem - found [this texture pack](http://www.planetminecraft.com/texture_pack/173-texture-pack/) when randomly looking for something to test with. Loading it crashes the launcher, which should not crash no matter what I put in `~/.truecraft/texturepacks`. This is an invalid texture pack, so it's cool that it doesn't work, but we can't be crashing because of it. Do you have a texture pack I could test with?

**Comment by mrpimpunicorn** [comment]
I've been using [Dokucraft](http://www.planetminecraft.com/texture_pack/dokucraft-175-beta/) to test with.

**Comment by mrpimpunicorn** [comment]
Okay, now I see the issue. We need a default pack.png and pack.txt to use if the texture pack doesn't provide one.

**Comment by SirCmpwn** [comment]
I get this when running with DokuCraft in `~/.truecraft/texturepacks`:

    sircmpwn@kyouko ~/s/T/T/b/Debug (HEAD detached at mrpimpunicorn/master)> mono --debug TrueCraft.Launcher.exe

    Unhandled Exception:
    System.ArgumentNullException: Argument cannot be null.
    Parameter name: stream
      at Gdk.PixbufLoader.InitFromStream (System.IO.Stream stream) [0x0002a] in /build/gtk-sharp-2/src/gtk-sharp-2.12.22/gdk/generated/PixbufLoader.custom:84 
      at Gdk.PixbufLoader..ctor (System.IO.Stream stream) [0x00009] in /build/gtk-sharp-2/src/gtk-sharp-2.12.22/gdk/generated/PixbufLoader.custom:71 
      at Xwt.GtkBackend.ImageHandler.LoadFromStream (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
      at Xwt.Drawing.Image.FromStream (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
      at TrueCraft.Launcher.Views.OptionView.AddTexturePackRow (TrueCraft.Core.TexturePack pack) [0x00020] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Views/OptionView.cs:116 
      at TrueCraft.Launcher.Views.OptionView.LoadTexturePacks () [0x00086] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Views/OptionView.cs:109 
      at TrueCraft.Launcher.Views.OptionView..ctor (TrueCraft.Launcher.LauncherWindow window) [0x001bf] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Views/OptionView.cs:81 
      at (wrapper remoting-invoke-with-check) TrueCraft.Launcher.Views.OptionView:.ctor (TrueCraft.Launcher.LauncherWindow)
      at TrueCraft.Launcher.LauncherWindow..ctor () [0x0006f] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/LauncherWindow.cs:35 
      at (wrapper remoting-invoke-with-check) TrueCraft.Launcher.LauncherWindow:.ctor ()
      at TrueCraft.Launcher.Program.Main (System.String[] args) [0x00080] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Program.cs:27 
    [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Argument cannot be null.
    Parameter name: stream
      at Gdk.PixbufLoader.InitFromStream (System.IO.Stream stream) [0x0002a] in /build/gtk-sharp-2/src/gtk-sharp-2.12.22/gdk/generated/PixbufLoader.custom:84 
      at Gdk.PixbufLoader..ctor (System.IO.Stream stream) [0x00009] in /build/gtk-sharp-2/src/gtk-sharp-2.12.22/gdk/generated/PixbufLoader.custom:71 
      at Xwt.GtkBackend.ImageHandler.LoadFromStream (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
      at Xwt.Drawing.Image.FromStream (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
      at TrueCraft.Launcher.Views.OptionView.AddTexturePackRow (TrueCraft.Core.TexturePack pack) [0x00020] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Views/OptionView.cs:116 
      at TrueCraft.Launcher.Views.OptionView.LoadTexturePacks () [0x00086] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Views/OptionView.cs:109 
      at TrueCraft.Launcher.Views.OptionView..ctor (TrueCraft.Launcher.LauncherWindow window) [0x001bf] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Views/OptionView.cs:81 
      at (wrapper remoting-invoke-with-check) TrueCraft.Launcher.Views.OptionView:.ctor (TrueCraft.Launcher.LauncherWindow)
      at TrueCraft.Launcher.LauncherWindow..ctor () [0x0006f] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/LauncherWindow.cs:35 
      at (wrapper remoting-invoke-with-check) TrueCraft.Launcher.LauncherWindow:.ctor ()
      at TrueCraft.Launcher.Program.Main (System.String[] args) [0x00080] in /home/sircmpwn/sources/TrueCraft/TrueCraft.Launcher/Program.cs:27

**Comment by SirCmpwn** [comment]
Oh, my bad, DokuCraft contains the texture pack zip inside of the download zip.

**Comment by mrpimpunicorn** [comment]
I just need to work out the edge cases in the launcher then; I've already written the TextureMapper for the client and it works fine.

**Comment by mrpimpunicorn** [comment]
Hopefully that fixes it.

**Comment by SirCmpwn** [comment]
Better, but a few issues:

* Running with the cwd set to anything other than `bin/Debug/` still doesn't work
* Now the default texture pack has a `?` icon and no description

**Comment by SirCmpwn** [comment]
Does this handle the case where there's file in `~/.truecraft/texturepacks` that is not a zip file, or a corrupted zip file?

**Comment by mrpimpunicorn** [comment]
It skips over non-zip files, but not corrupted ones. I'll write another commit for those 3 things.

**Comment by SirCmpwn** [comment]
Cool, thanks. Sorry for the long review, this is a complex feature.

**Comment by mrpimpunicorn** [comment]
It's fine, I totally understand.

**Comment by mrpimpunicorn** [comment]
Okay, I think it's all working now. I'm definitely going to have to refactor the code and clean up a bit later, but the feature is there.

**Comment by SirCmpwn** [comment]
I merged this manually, but Github got confused, so closing the PR. Thanks!

**Pull request closed without merging**
