### PR TITLE
Check Gtk version on Linux

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Wouldn't this only work if the -dev package is installed on debian derivatives and other distros that don't include headers et al by default?

**Comment by cra0zy** [comment]
Oh yea.. I got used to Arch that I forgot about the split with the other distros... don't worry I have a plan B that requires try catch :)

**Comment by SirCmpwn** [comment]
Cool, looking forward to it.

**Comment by cra0zy** [comment]
What do you think?

**Comment by SirCmpwn** [comment]
Oh lord

**Comment by SirCmpwn** [comment]
I would rather just see a solution for this via https://github.com/mono/xwt/issues/591

**Comment by cra0zy** [comment]
> Oh lord

It's a good way of doing it... what's wrong with it?

> I would rather just see a solution for this via mono/xwt#591

It's gonna take them a long time to do it, just look at how much activity all the other issues had O o. My way on the other hand works, and can be used until they implement a way.

PS. I can't launch TrueCraft with Gtk 2 because I don't have gtk2 webkit installed on my system.

PPS. I use Eto.Forms instead of Xwt these days.

**Comment by SirCmpwn** [comment]
>It's a good way of doing it... what's wrong with it?

I'm not a fan, it seems hacky and fragile.

>It's gonna take them a long time to do it, just look at how much activity all the other issues had O o. My way on the other hand works, and can be used until they implement a way.

I'm suggesting that you implement it and send them a PR :)

>PS. I can't launch TrueCraft with Gtk 2 because I don't have gtk2 webkit installed on my system.

Well, install it or just run the client directly.

>PPS. I use Eto.Forms instead of Xwt these days.

Well, TrueCraft uses Xwt.

**Comment by cra0zy** [comment]
> I'm not a fan, it seems hacky and fragile.

Hacky, yes, fragile, no.

**Comment by flibitijibibo** [comment]
I believe this is now obsoleted by #271?

**Comment by cra0zy** [comment]
Well kind of forgot I had this opened... tho I do know of a non hacky way to do this now,

@SirCmpwn Just a warning, webkitgtk is being removed from a lot of distros because it is unseccure, Arch Linux already dropped it, so if you are planning on using Gtk 3 you need to use webkit2gtk, which Xwt is not using.

**Comment by SirCmpwn** [comment]
Of course *now* I remember why I didn't want to use GTK3. Thanks, @cra0zy.

**Comment by SirCmpwn** [comment]
https://github.com/mono/xwt/issues/713

**Comment by cra0zy** [comment]
I'll just point out that I updated Etos Gtk 3 backend to webkit 2, might be useful if you want to do it on the Xwt side: https://github.com/picoe/Eto/pull/747 (or if you want to switch to Eto :P)

**Comment by BearzRobotics** [comment]
I have it compiled on two (Solus) systems using gtk3 and the launcher and webview works fine. The only problem it had was an ssl certificate. which even Firefox complained about going to truecraft.io. 

In the '[Xwt.Gtk3.dll.config](https://github.com/SirCmpwn/TrueCraft/blob/master/lib/Xwt.Gtk3.dll.config)' by default it uses libwebkitgtk-3.0.so.0

**Comment by cra0zy** [comment]
> I have it compiled on two (Solus) systems using gtk3 and the launcher and webview works fine. The only problem it had was an ssl certificate. which even Firefox complained about going to truecraft.io.
> 
> In the 'Xwt.Gtk3.dll.config' by default it uses libwebkitgtk-3.0.so.0

That is webkit 1 library for gtk 3, and it is already gone from Arch Linux, the webkit 2 library is libwebkit2gtk-4.0.so.37...

**Comment by BearzRobotics** [comment]
Okay Thanks for the correction.

**Pull request closed without merging**
