### PR TITLE
Added cobweb renderer

### PR DESCRIPTION
**Pull request by mrpimpunicorn**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
In theory this can be a lot simpler. Take a look at [sugarcane](https://github.com/SirCmpwn/TrueCraft/blob/master/TrueCraft.Client/Rendering/Blocks/SugarcaneRenderer.cs).

**Comment by mrpimpunicorn** [comment]
Oops.

**Comment by mrpimpunicorn** [comment]
By the way, I was going to add slab rendering but there doesn't seem to be a ```WoodSlabBlock``` or ```CobblestoneSlabBlock```?

**Comment by SirCmpwn** [comment]
I don't know about that. They might be using another name. If not, add them.

**Comment by mrpimpunicorn** [comment]
Actually there just seems to be two blocks; full slabs (42) and half slabs (44), they both use data values to store block type; I'll just check that in the renderer and use the appropriate texture.

**Comment by SirCmpwn** [comment]
Cool.

**Pull request merged**
