### PR TITLE
Make RenderThreadState a class instead of a struct

### PR DESCRIPTION
**Pull request by Mitch528**
Structs can't have parameterless constructors

### CODE REVIEW

**Comment by SirCmpwn** [comment]
>Structs can't have parameterless constructors

...yes they can

**Comment by SirCmpwn** [comment]
This also includes a bunch of unrelated changes.

**Comment by SirCmpwn** [comment]
From IRC:

* I'm unwittingly using a C# 6 feature here
* The unrelated changes are necessary to make the build work on Windows

Next steps:

* C# 6 is too young to expect everyone to have access to, so I'll merge this when:
* The Windows build changes are put into their own commit

**Comment by SirCmpwn** [comment]
Thanks, @Mitch528. Just to be sure - have you ever read the decompiled Minecraft source code?

**Comment by Mitch528** [comment]
No, I haven't.

**Comment by SirCmpwn** [comment]
Awesome, thanks!

**Pull request merged**
